import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { label: "Home", href: "/" },
  { label: "Work", href: "work" },
  { label: "Contact", href: "contact" },
  { label: "About me" },
  { label: "Pricing" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex w-full bg-background/10 fixed top-0 left-0 text-foreground text-2xl font-semibold items-center justify-between p-8">
          {links.map(({ label, href }) => (
            <Link
              key={label}
              href={href ?? "/"}
              className="hover:text-foreground/80  transition-all hover:-translate-y-1 py-1 hover:tracking-wider hover:scale-110"
            >
              {label}
            </Link>
          ))}
        </nav>
        <main className="pt-28">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
